---

language: minimal
services:
  - docker
  - ntp
  - xvfb
addons:
  chrome: stable

jobs:
  include:
    - stage: test
      script:
        - ./tests/resources/run_all_suites.sh

after_success:
  - ./scripts/deploy_dockerhub.sh
